version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_lumi
    restart: always
    environment:
      POSTGRES_USER: lumi_admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: energia_lumi
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
